name: zenden_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pimp_my_button:
    git:
      url: git://github.com/Norbert515/pimp_my_button.git
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: 0.7.0
  google_sign_in: 3.2.4
  cloud_firestore: 0.8.2+3
  fluttertoast: ^2.0.7
  image_picker: 0.4.12+1
  shared_preferences: 0.4.3
  firebase_storage: 1.0.4
  cached_network_image: ^0.7.0
  carousel_slider: ^1.3.0
  font_awesome_flutter: ^8.4.0
  firebase_dynamic_links: ^0.3.0
  google_maps_flutter: ^0.0.3+3
  flutter_google_places: ^0.1.4+1
  geocoder: ^0.1.2
  intl: ^0.15.7
  flutter_tindercard: ^0.1.8
  firebase_messaging: 5.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  assets:
  - assets/zenden_logo.png
  - assets/background.gif
  - assets/house.jpg
  - assets/h1.jpg
  - assets/h2.jpg

  fonts:
  - family: Lobster
    fonts:
    - asset: fonts/Lobster-Regular.ttf
  - family: Katibeh
    fonts:
    - asset: fonts/Katibeh-Regular.ttf
  - family: Grenze
    fonts:
    - asset: fonts/Grenze-Regular.ttf

  uses-material-design: true


